In [5]:
import numpy as np
import torch

In [6]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [7]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [8]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-1.0285, -0.5744, -0.2944],
        [-1.2825,  0.3523, -0.1072]], requires_grad=True)
tensor([-1.5388, -0.7198], requires_grad=True)


In [9]:
# Linear regression 
def model(x):
    return x @ w.t() + b

In [10]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-127.7593,  -75.3480],
        [-164.5157,  -93.2861],
        [-185.0573,  -71.3052],
        [-142.0339, -120.3535],
        [-148.2503,  -62.8956]], grad_fn=<AddBackward0>)


Output very off in start