In [33]:
import numpy as np
import torch

In [34]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [35]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [36]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.1198,  1.6646, -0.9860],
        [ 0.7007, -0.1475,  1.2371]], requires_grad=True)
tensor([-0.6641, -0.7647], requires_grad=True)


In [37]:
# Linear regression 
def model(x):
    return x @ w.t() + b

In [38]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 59.7216,  93.6995],
        [ 71.8158, 129.1944],
        [154.7845, 112.1850],
        [ 22.2124, 110.1352],
        [ 81.8522, 120.0229]], grad_fn=<AddBackward0>)


In [39]:
# Creating a lost function
def mse(t1,t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [40]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(896.5669, grad_fn=<DivBackward0>)


### Compute Gradients

In [41]:
loss.backward()

In [42]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.1198,  1.6646, -0.9860],
        [ 0.7007, -0.1475,  1.2371]], requires_grad=True)
tensor([[ 222.3291,  443.0434,   35.0524],
        [2003.0439,  904.5544,  878.7706]])


### Training

In [52]:
# we will train for 200 epochs
for epoch in range(300):
    preds = model(inputs) # prediction 
    loss = mse(preds, targets) # calculate loss
    loss.backward() # calculate gradients
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
    if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, 300, loss.item()))

Epoch [10/300], Loss: nan
Epoch [20/300], Loss: nan
Epoch [30/300], Loss: nan
Epoch [40/300], Loss: nan
Epoch [50/300], Loss: nan
Epoch [60/300], Loss: nan
Epoch [70/300], Loss: nan
Epoch [80/300], Loss: nan
Epoch [90/300], Loss: nan
Epoch [100/300], Loss: nan
Epoch [110/300], Loss: nan
Epoch [120/300], Loss: nan
Epoch [130/300], Loss: nan
Epoch [140/300], Loss: nan
Epoch [150/300], Loss: nan
Epoch [160/300], Loss: nan
Epoch [170/300], Loss: nan
Epoch [180/300], Loss: nan
Epoch [190/300], Loss: nan
Epoch [200/300], Loss: nan
Epoch [210/300], Loss: nan
Epoch [220/300], Loss: nan
Epoch [230/300], Loss: nan
Epoch [240/300], Loss: nan
Epoch [250/300], Loss: nan
Epoch [260/300], Loss: nan
Epoch [270/300], Loss: nan
Epoch [280/300], Loss: nan
Epoch [290/300], Loss: nan
Epoch [300/300], Loss: nan


In [46]:
preds = model(inputs)
print(preds)

tensor([[nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan]], grad_fn=<AddBackward0>)
